# Generated by Django 3.1.7 on 2021-03-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210320_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.expert_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Blogpost_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_tag')),
            ],
        ),
    ]
